import { useState } from 'react';
import { AiAPI } from '../services/api.js';
import { NOTARY_SERVICES } from '../store/constants.js';
import Modal from './Modal.jsx';
import Button from './Button.jsx';
import FormField from './FormField.jsx';
import { useToast } from '../store/hooks.js';

export default function AiDraftGeneratorModal({ open, onClose, initialService = 'AJB' }) {
  const { notify } = useToast();
  const [serviceType, setServiceType] = useState(initialService);
  const [params, setParams] = useState({
    pihak1: 'PIHAK PERTAMA (Penjual / Pemohon)',
    pihak2: 'PIHAK KEDUA (Pembeli / Penerima)',
    objek: 'Tanah & Bangunan SHM No. 123/Kel. Merdeka',
    harga: 'Rp 750.000.000 (Tujuh Ratus Lima Puluh Juta Rupiah)',
  });
  const [generatedClause, setGeneratedClause] = useState('');
  const [loading, setLoading] = useState(false);
  const [engineUsed, setEngineUsed] = useState('');

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await AiAPI.generateDraft(serviceType, params);
      if (res.success && res.clauseText) {
        setGeneratedClause(res.clauseText);
        setEngineUsed(res.engine || 'Local AI Engine');
        notify('Draft pasal berhasil dibuat oleh AI Lokal!', 'success');
      }
    } catch (err) {
      notify('Gagal menghasilkan draft pasal AI', 'danger');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!generatedClause) return;
    navigator.clipboard.writeText(generatedClause);
    notify('Draft pasal berhasil disalin ke clipboard!', 'info');
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="AI Legal Clause & Draft Akta Generator"
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>
            Tutup
          </Button>
          {generatedClause && (
            <Button variant="primary" icon="fileText" onClick={handleCopy}>
              Salin Teks Pasal
            </Button>
          )}
        </>
      }
    >
      <div className="form-grid">
        <FormField label="Jenis Layanan Notaris">
          <select value={serviceType} onChange={(e) => setServiceType(e.target.value)}>
            {NOTARY_SERVICES.map((s) => (
              <option key={s.id} value={s.id}>
                {s.name}
              </option>
            ))}
          </select>
        </FormField>
        <FormField label="Pihak Pertama">
          <input
            type="text"
            value={params.pihak1}
            onChange={(e) => setParams({ ...params, pihak1: e.target.value })}
          />
        </FormField>
        <FormField label="Pihak Kedua">
          <input
            type="text"
            value={params.pihak2}
            onChange={(e) => setParams({ ...params, pihak2: e.target.value })}
          />
        </FormField>
        <FormField label="Objek Akta / Perjanjian">
          <input
            type="text"
            value={params.objek}
            onChange={(e) => setParams({ ...params, objek: e.target.value })}
          />
        </FormField>
      </div>

      <div className="mt-3">
        <FormField label="Nilai Transaksi / Catatan Tambahan (Opsional)">
          <input
            type="text"
            value={params.harga}
            onChange={(e) => setParams({ ...params, harga: e.target.value })}
          />
        </FormField>
      </div>

      <div className="mt-4 mb-4">
        <Button variant="primary" icon="activity" onClick={handleGenerate} disabled={loading} style={{ width: '100%' }}>
          {loading ? 'AI Sedang Merancang Draft Pasal...' : 'Generate Draft Pasal Notaris dengan AI'}
        </Button>
      </div>

      {generatedClause && (
        <div style={{ background: 'var(--surface-2)', color: 'var(--text)', padding: '1rem', borderRadius: 'var(--radius-sm)', fontFamily: 'monospace', fontSize: '0.85rem', whiteSpace: 'pre-line', maxHeight: '250px', overflowY: 'auto', border: '1px solid var(--border)' }}>
          <div style={{ color: 'var(--text-2)', fontSize: '0.75rem', marginBottom: '0.5rem', fontWeight: 600 }}>
            Generated by: {engineUsed} (100% Offline)
          </div>
          {generatedClause}
        </div>
      )}
    </Modal>
  );
}
